Test queries are resolved by the DNS  server
Co-authored-by: Andy Mitchell <me@themitchell.co.uk>

diff --git a/dns-service/dns_test b/dns-service/dns_test
--- a/dns-service/dns_test
+++ b/dns-service/dns_test
@@ -5,9 +5,20 @@ echo "Running dnsperf..."
 # -d query file path
 # -c number of clients
 # -Q nuber of requests per second
-# -t timeout (seconds)
+# -t timmeout (seconds)
 dnsperf -s dns \
         -d test_queryfile \
         -c 1 \
         -Q 10 \
-        -t 15
+        -t 15 > ./test_result
+
+has_completed_all_queries=`cat ./test_result | grep "Queries completed:    11 (100.00%)"`
+
+if [[ -n $has_completed_all_queries ]]; then
+  echo "Succeeded querying"
+  exit 0
+else
+  echo "Failed querying"
+  cat ./test_result
+  exit 1
+fi
